### PR TITLE
Multiple updates

### PR DESCRIPTION
**Pull request by hugomcfonseca**
This PR contains multiple updates to reflect current API endpoints and parameters.

Major improvements were done at:

- Separate component_groups from components and incident_updates from incident to keep same syntax for function names
- Improved current tests and added new tests for new endpoints and parameters (I am still planning to add new tests for testing other features)
- Merge querystring parameters to contains all available filters for any endpoint and also parameters that are specific to a given endpoint
- Others

I know it is an huge pull request, so feel free to ask me anything about it.

### CODE REVIEW

**Comment by andygrunwald** [comment]
Thanks, Hugo!
Indeed, this PR is huge. I might need some time to review it.
At first, I would suggest to make the unit tests pass because right now there are a couple of errors (structs are not defined and so on). See https://travis-ci.org/andygrunwald/cachet/builds/356494075?utm_source=github_status&utm_medium=notification for details.

**Comment by hugomcfonseca** [comment]
Yes @andygrunwald, sorry about that. I think it made a mistake when I merged my fork with your repo before creating this PR. I will fix it.

**Comment by hugomcfonseca** [comment]
I had to temporarily remove `tags` from components' response. It happened because JSON is not well-defined at the moment, and will suffer some modifications in the future. A brief overview about the problem: currently, tags are returned as an duplicated key-value format (example: `"tags":{"test":"test","as":"as","war":"war"}`), so our structs are not prepared for it.

I open an issue related to this in Cachet repo ([#2952](https://github.com/CachetHQ/Cachet/issues/2952)).

**Comment by hugomcfonseca** [comment]
@andygrunwald any other problem or question, just ask. Also, if you have some ideas for extra tests, just tell me. I would like to help you to improve this project.

**Comment by andygrunwald** [comment]
Incredible update!
Thanks a lot @hugomcfonseca!
It took me some time to review it. Sorry, but this was huge. Heavy effort!
I think a lot of people can benefit from your contribution!

**Comment by hugomcfonseca** [comment]
Thanks, @andygrunwald! It was a pleasure, I am start working with Go and this project helped me a lot, it is really well-structured and makes any improvement really easier.

Since Cachet v2.4 is still under development, I will keep my eyes on it and as soon as any changes on API happens, I will try to keep this client updated. There are a few things I want to improve, mostly related to the **components tags** that would improve components' searching.

**Comment by andygrunwald** [comment]
Feel free. I try to react quicker next time!

**Pull request merged**
